apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mysite-daemonset
  labels:
    app: mysite-daemonset
spec:
  selector:
    matchLabels:
      app: mysite-daemonset
  template:
    metadata:
      labels:
        app : mysite-daemonset
    spec:
      containers:
      - name: nginx
        image: nginx
